# Generated by Django 5.0.6 on 2024-05-15 10:42

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=15, verbose_name='Название дисциплины')),
            ],
            options={
                'verbose_name': 'Дисциплина уличного спорта',
                'verbose_name_plural': 'Дисциплины уличного спорта',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название мероприятия', max_length=150, verbose_name='Название мероприятия')),
                ('description', models.TextField(help_text='Введите описание мероприятия', max_length=10000, verbose_name='Описание')),
                ('date', models.DateField(help_text='Введите дату мероприятия', verbose_name='Дата проведения')),
                ('type_of_area', models.CharField(choices=[('OPEN', 'Открытая'), ('CLOSED', 'Закрытая')], help_text='Выберите тип площадки', max_length=20, verbose_name='Тип площадки')),
                ('plan_of_event', models.CharField(help_text='Введите план мероприятия', max_length=10000, verbose_name='План мероприятия')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес площадки')),
                ('is_moderation', models.BooleanField(default=False)),
                ('organizers_contact', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(verbose_name='Связь с организатором'), blank=True, help_text='Введите ссылку на связь с организаторами', null=True, size=None)),
                ('count_entrant', models.IntegerField(default=0)),
                ('city', models.ForeignKey(help_text='Выберите город', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.city', verbose_name='Город проведения')),
                ('discipline_of_event', models.ForeignKey(help_text='Выберите дисциплину уличного спорта', on_delete=django.db.models.deletion.CASCADE, to='events.discipline', verbose_name='Дисциплина уличного спорта')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='GalleryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files_events/', verbose_name='Файл')),
                ('event', models.ForeignKey(help_text='Медиа-файлы, связанные с этим мероприятием', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_events', to='events.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Галерея меропрития',
            },
        ),
    ]
