# Generated by Django 5.0.6 on 2024-05-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, help_text='Выберите фотографию', upload_to='pictures_events/', verbose_name='Картинка меропрития')),
                ('title', models.CharField(help_text='Введите название мероприятия', max_length=150, unique=True, verbose_name='Название мероприятия')),
                ('description', models.TextField(help_text='Введите описание мероприятия', max_length=10000, verbose_name='Описание')),
                ('date', models.DateField(help_text='Введите дату мероприятия', verbose_name='Дата проведения')),
                ('discipline_of_event', models.CharField(choices=[('STREET ART', 'STREET ART'), ('PARKOUR', 'PARKOUR'), ('WORKOUT', 'WORKOUT'), ('FREERUN', 'FREERUN'), ('HIP-HOP DANCE', 'HIP-HOP DANCE'), ('TRICKING', 'TRICKING'), ('RAP', 'RAP'), ('BREAKING', 'BREAKING'), ('BMX', 'BMX'), ('SCOOT', 'SCOOT')], max_length=15, verbose_name='Дисциплина')),
                ('type_of_area', models.CharField(choices=[('OPEN', 'Открытая'), ('CLOSED', 'Закрытая')], max_length=20, verbose_name='Тип площадки')),
                ('plan_of_event', models.CharField(max_length=15, verbose_name='План мероприятия')),
                ('city', models.CharField(choices=[('Moscow', 'Москва'), ('Saint Petersburg', 'Санкт-Петербург'), ('Novosibirsk', 'Новосибирск'), ('Yekaterinburg', 'Екатеринбург'), ('Nizhny Novgorod', 'Нижний Новгород'), ('Kazan', 'Казань'), ('Chelyabinsk', 'Челябинск'), ('Omsk', 'Омск'), ('Samara', 'Самара'), ('Rostov-on-Don', 'Ростов-на-Дону'), ('Ufa', 'Уфа'), ('Krasnoyarsk', 'Красноярск'), ('Perm', 'Пермь'), ('Voronezh', 'Воронеж'), ('Volgograd', 'Волгоград'), ('Krasnodar', 'Краснодар'), ('Saratov', 'Саратов'), ('Tyumen', 'Тюмень'), ('Izhevsk', 'Ижевск'), ('Ulyanovsk', 'Ульяновск'), ('Barnaul', 'Барнаул'), ('Irkutsk', 'Иркутск'), ('Khabarovsk', 'Хабаровск'), ('Yaroslavl', 'Ярославль')], max_length=20, verbose_name='Город проведения')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес площадки')),
                ('is_moderation', models.BooleanField(default=False)),
                ('additional_fields', models.JSONField(blank=True, help_text='Дополнительные поля в формате JSON', null=True, verbose_name='Дополнительные поля')),
                ('count_entrant', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
