# Generated by Django 5.0.6 on 2024-05-15 12:30

import file_validator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryevent',
            name='file',
            field=models.FileField(help_text='Загрузите файл.', upload_to='files_events/', validators=[file_validator.models.DjangoFileValidator(acceptable_types=['audio', 'video', 'image'], max_upload_file_size=10485760)], verbose_name='Файл'),
        ),
    ]
