# Generated by Django 3.2.18 on 2024-05-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Введите название площадки', max_length=150, verbose_name='Название площадки'),
        ),
    ]
