version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db_container
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - street_net

  # web:
  #   build:
  #     context: ./backend
  #   command: gunicorn streets_russia.wsgi:application --bind 0.0.0.0:8000
  #   volumes:
  #     - ./backend:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #     - redis
  #   env_file:
  #     - .env
  #   networks:
  #     - street_net

  celery:
    build:
      context: ./backend
    command: celery -A streets_russia worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=streets_russia.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - street_net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - street_net

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - street_net


volumes:
  postgres_data:

networks:
  street_net: