version: '3.8'

services:
  db:
    image: postgres:15-alpine3.18
    container_name: db_container
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - street_net


volumes:
  postgres_data:

networks:
  street_net: