version: '3.8'

services:
  db:
    container_name: street_russia-db
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    container_name: street_russia-backend
    depends_on:
      - db
    restart: always
    image: dnevskiy/streets_backend
    volumes:
      - static:/app/static/
    env_file:
      - .env

  celery:
    image: dnevskiy/streets_backend
    command: celery -A streets_russia worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=streets_russia.settings
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  nginx:
    container_name: street_russia-nginx
    depends_on:
      - web
    restart: always
    image: dnevskiy/streets_nginx
    volumes:
      - static:/app/static/
    ports:
      - "8500:80"

volumes:
  static:
  db_data: