# Generated by Django 3.2.18 on 2024-05-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='consent_to_rights',
            field=models.BooleanField(verbose_name='Согласие с правилами'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='passport_issue_date',
            field=models.DateField(verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='сonsent_to_processing',
            field=models.BooleanField(verbose_name='Согласие на обработку данных'),
        ),
    ]
